services:
  - type: web
    name: seia-site-planner
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: seia_site_planner
      - key: MONGODB_COLLECTION
        value: sessions
